=== nvanhai/tct2013/Source/NTKCC3.2_PIT/source/TaxProjectServer/InterfaceTemplates/Schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by ThanhDX (FSS - HN) -->
<!ATTLIST Cell
	CellID ID #REQUIRED
	FirstCell CDATA #IMPLIED
	Value CDATA #REQUIRED
	MCT CDATA #IMPLIED
	Encode CDATA #IMPLIED
	Receive CDATA #IMPLIED
	MaxLen CDATA #IMPLIED
	MinValue CDATA #IMPLIED
	MaxValue CDATA #IMPLIED
	HelpContexID CDATA #IMPLIED
>
<!ELEMENT Dynamic (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Cell (#PCDATA)>
<!ELEMENT Value (#PCDATA)>
<!ELEMENT Cells (Cell+)>
<!ATTLIST Section
	Dynamic CDATA #REQUIRED
	MaxRows CDATA #REQUIRED
	DateKHBS CDATA #IMPLIED
	loaiKHBS CDATA #IMPLIED
>
<!ELEMENT Section (Cells+)>
<!ELEMENT Sections (Section+)>

=== nvanhai/tct2013/Source/NTKCC3.2_PIT/source/TaxProjectServer/DataFiles/02_GTGT_052010.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_4" Value=""/>
			<Cell CellID="G_5" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="M_8" Value=""/>
			<Cell CellID="V_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="M_10" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_16" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_14" Value=""/>
			<Cell CellID="M_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_10" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_18" Value="" MaxLen="1000"/>
			<Cell CellID="W_21" Value="0" MCT="10"/>
			<Cell CellID="Q_23" Value="20000000" MCT="11"/>
			<Cell CellID="W_23" Value="2000000" MCT="12"/>
			<Cell CellID="Q_24" Value="10000000" MCT="13"/>
			<Cell CellID="W_24" Value="1000000" MCT="14"/>
			<Cell CellID="Q_25" Value="10000000" MCT="15"/>
			<Cell CellID="W_25" Value="1000000" MCT="16"/>
			<Cell CellID="Q_27" Value="10000000" MCT="17"/>
			<Cell CellID="W_27" Value="1000000" MCT="18"/>
			<Cell CellID="Q_28" Value="30000000" MCT="19"/>
			<Cell CellID="W_28" Value="2000000" MCT="20"/>
			<Cell CellID="W_29" Value="1000000" MCT="21"/>
			<Cell CellID="W_30" Value="1000000" MCT="22"/>
			<Cell CellID="W_31" Value="1000000" MCT="23"/>
			<Cell CellID="W_32" Value="0" MCT="24"/>
			<Cell CellID="W_33" Value="0" MCT="25"/>
			<Cell CellID="T_35" Value="" MCT="26"/>
			<Cell CellID="T_36" Value="" MCT="27"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKCC3.2_PIT/source/TaxProjectServer/DataFiles/01_1_TTDB_062010.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_4" Value=""/>
			<Cell CellID="G_5" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="M_8" Value=""/>
			<Cell CellID="V_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="M_10" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_16" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_14" Value=""/>
			<Cell CellID="M_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_10" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_25" FirstCell="0" Value="fdgd" MCT="2"/>
			<Cell CellID="D_25" Value="2" MCT="3"/>
			<Cell CellID="E_25" Value="01/01/2010" MCT="4"/>
			<Cell CellID="F_25" Value="fdgf" MCT="5"/>
			<Cell CellID="I_25" Value="10101" MCT="6"/>
			<Cell CellID="J_25" Value="fsdfsd" MCT="7"/>
			<Cell CellID="N_25" Value="100.00" MCT="8"/>
			<Cell CellID="O_25" Value="100000.00" MCT="9"/>
			<Cell CellID="P_25" Value="10000000" MCT="10"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="L_29" FirstCell="0" Value="Xì gà" MCT="11"/>
			<Cell CellID="N_29" Value="100.00"/>
			<Cell CellID="P_29" Value="10000000"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKCC3.2_PIT/source/TaxProjectServer/DataFiles/02A_TNCN_012009.xml
<!-- Edited by htphuong FIS_CMC-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_4" Value=""/>
			<Cell CellID="G_5" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="M_8" Value=""/>
			<Cell CellID="V_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="M_10" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_16" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_14" Value=""/>
			<Cell CellID="M_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_10" Value="" MaxLen="60"/>
			<Cell CellID="E_36" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="U_40" Value="100000" MCT="1"/>
			<Cell CellID="U_41" Value="10000000" MCT="2"/>
			<Cell CellID="U_42" Value="50000" MCT="3"/>
			<Cell CellID="U_43" Value="8000000" MCT="4"/>
			<Cell CellID="U_44" Value="200" MCT="5"/>
			<Cell CellID="U_45" Value="100000" MCT="6"/>
			<Cell CellID="U_49" Value="20" MCT="7"/>
			<Cell CellID="U_50" Value="10" MCT="8"/>
			<Cell CellID="U_51" Value="10" MCT="9"/>
			<Cell CellID="U_52" Value="90000000" MCT="10"/>
			<Cell CellID="U_53" Value="50000000" MCT="11"/>
			<Cell CellID="U_54" Value="40000000" MCT="12"/>
			<Cell CellID="U_55" Value="13000000" MCT="13"/>
			<Cell CellID="U_56" Value="5000000" MCT="14"/>
			<Cell CellID="U_57" Value="8000000" MCT="15"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="R_59" Value="Hà Thế Phương"/>
			<Cell CellID="R_61" Value="13/02/2009"/>
			<Cell CellID="C_62" Value="1"/>
			<Cell CellID="F_62" Value=""/>
			<Cell CellID="I_62" Value=""/>
			<Cell CellID="C_37" Value=""/>
			<Cell CellID="C_46" Value=""/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKCC3.2_PIT/source/TaxProjectServer/DataFiles/01_TTDB_092010.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="J_4" Value=""/>
			<Cell CellID="J_5" Value=""/>
			<Cell CellID="J_6" Value=""/>
			<Cell CellID="J_7" Value=""/>
			<Cell CellID="T_7" Value=""/>
			<Cell CellID="AC_7" Value=""/>
			<Cell CellID="I_10" Value=""/>
			<Cell CellID="I_12" Value=""/>
			<Cell CellID="T_12" Value=""/>
			<Cell CellID="AC_12" Value=""/>
			<Cell CellID="T_10" Value="" MaxLen="20"/>
			<Cell CellID="AC_16" Value="" MinValue="0" MaxValue="9999999999"/>
			<Cell CellID="I_14" Value=""/>
			<Cell CellID="T_14" Value="" MaxLen="100"/>
			<Cell CellID="AC_10" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="M_17" Value="" MCT="1"/>
			<Cell CellID="W_28" Value="256666666" MCT="3"/>
			<Cell CellID="AB_28" Value="166545454.00" MCT="4"/>
			<Cell CellID="AG_28" Value="0" MCT="5"/>
			<Cell CellID="AJ_28" Value="0" MCT="6"/>
			<Cell CellID="AN_28" Value="90121212" MCT="7"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="D_31" FirstCell="0" Value="10103" MCT="8"/>
			<Cell CellID="O_31" Value="Lít" MCT="9"/>
			<Cell CellID="R_31" Value="8.00" MCT="10"/>
			<Cell CellID="W_31" Value="200000000" MCT="11"/>
			<Cell CellID="AB_31" Value="121212121.00" MCT="12"/>
			<Cell CellID="AD_31" Value="65.0" MCT="13"/>
			<Cell CellID="AG_31" Value="0" MCT="14"/>
			<Cell CellID="AJ_31" Value="0" MCT="15"/>
			<Cell CellID="AN_31" Value="78787879" MCT="16"/>
		</Cells>
		<Cells>
			<Cell CellID="D_32" FirstCell="1" Value="10203" MCT="8"/>
			<Cell CellID="O_32" Value="Lít" MCT="9"/>
			<Cell CellID="R_32" Value="5666.00" MCT="10"/>
			<Cell CellID="W_32" Value="56666666" MCT="11"/>
			<Cell CellID="AB_32" Value="45333333.00" MCT="12"/>
			<Cell CellID="AD_32" Value="25.0" MCT="13"/>
			<Cell CellID="AG_32" Value="0" MCT="14"/>
			<Cell CellID="AJ_32" Value="0" MCT="15"/>
			<Cell CellID="AN_32" Value="11333333" MCT="16"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="W_34" Value="800000" MCT="17"/>
			<Cell CellID="AB_34" Value="615385.00" MCT="18"/>
			<Cell CellID="AG_34" Value="0" MCT="19"/>
			<Cell CellID="AJ_34" Value="0" MCT="20"/>
			<Cell CellID="AN_34" Value="184616" MCT="21"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="D_36" FirstCell="0" Value="20102" MCT="22"/>
			<Cell CellID="O_36" Value="gio'" MCT="23"/>
			<Cell CellID="R_36" Value="800.00" MCT="24"/>
			<Cell CellID="W_36" Value="800000" MCT="25"/>
			<Cell CellID="AB_36" Value="615385.00" MCT="26"/>
			<Cell CellID="AD_36" Value="30.0" MCT="27"/>
			<Cell CellID="AG_36" Value="0" MCT="28"/>
			<Cell CellID="AJ_36" Value="0" MCT="29"/>
			<Cell CellID="AN_36" Value="184616" MCT="30"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="W_38" Value="42307876" MCT="31"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="D_42" FirstCell="0" Value="10102" MCT="32"/>
			<Cell CellID="O_42" Value="Bao" MCT="33"/>
			<Cell CellID="R_42" Value="6666.00" MCT="34"/>
			<Cell CellID="W_42" Value="45555" MCT="35"/>
		</Cells>
		<Cells>
			<Cell CellID="D_43" FirstCell="1" Value="10200" MCT="32"/>
			<Cell CellID="O_43" Value="Lít" MCT="33"/>
			<Cell CellID="R_43" Value="4555.00" MCT="34"/>
			<Cell CellID="W_43" Value="4455555" MCT="35"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="D_47" FirstCell="0" Value="10200" MCT="36"/>
			<Cell CellID="O_47" Value="Lít" MCT="37"/>
			<Cell CellID="R_47" Value="34.00" MCT="38"/>
			<Cell CellID="W_47" Value="3455555" MCT="39"/>
		</Cells>
		<Cells>
			<Cell CellID="D_48" FirstCell="1" Value="10203" MCT="36"/>
			<Cell CellID="O_48" Value="Lít" MCT="37"/>
			<Cell CellID="R_48" Value="34444.00" MCT="38"/>
			<Cell CellID="W_48" Value="34343434" MCT="39"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="D_52" FirstCell="0" Value="10200" MCT="40"/>
			<Cell CellID="O_52" Value="Lít" MCT="41"/>
			<Cell CellID="R_52" Value="35666666.00" MCT="42"/>
			<Cell CellID="W_52" Value="7777" MCT="43"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="W_54" Value="299774542" MCT="44"/>
			<Cell CellID="AB_54" Value="167160839.00" MCT="45"/>
			<Cell CellID="AG_54" Value="0" MCT="46"/>
			<Cell CellID="AJ_54" Value="0" MCT="47"/>
			<Cell CellID="AN_54" Value="90305828" MCT="48"/>
		</Cells>
	</Section>
</Sections>
