=== nvanhai/tct2013/Source/HTKK3.1.7/InterfaceIni/Schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by tuyends (FSS-HCM) -->
<!ATTLIST Cell
	CellID ID #REQUIRED
	MaxLen CDATA #IMPLIED
	MinValue CDATA #IMPLIED
	MaxValue CDATA #IMPLIED
	HelpContextID CDATA #REQUIRED
>
<!ELEMENT Dynamic (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Cell (#PCDATA)>
<!ELEMENT Cells (Cell+)>
<!ATTLIST Sections
	Version CDATA #IMPLIED
>
<!ATTLIST Section
	Dynamic CDATA #REQUIRED
	MaxRows CDATA #REQUIRED
>
<!ELEMENT Section (Cells+)>
<!ELEMENT Sections (Section+)>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/InterfaceTemplates/xml/03_GTGT13.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_10" Value=""/>
			<Cell CellID="H_8" Value=""/>
			<Cell CellID="F_12" Value=""/>
			<Cell CellID="F_16" Value=""/>
			<Cell CellID="N_16" Value=""/>
			<Cell CellID="V_16" Value=""/>
			<Cell CellID="E_30" Value=""/>
			<Cell CellID="E_32" Value=""/>
			<Cell CellID="M_32" Value=""/>
			<Cell CellID="V_32" Value=""/>
			<Cell CellID="M_30" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_39" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_36" Value=""/>
			<Cell CellID="M_36" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_30" Value=""/>

			<Cell CellID="H_18" Value=""/>
			<Cell CellID="F_22" Value=""/>
			<Cell CellID="F_26" Value=""/>
			<Cell CellID="N_26" Value=""/>
			<Cell CellID="V_26" Value=""/>
			<Cell CellID="H_28" Value=""/>
			<Cell CellID="N_28" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_20" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="Q_42" Value="0" MCT="21"/>
			<Cell CellID="Q_43" Value="0" MCT="22"/>
			<Cell CellID="Q_44" Value="0" MCT="23"/>
			<Cell CellID="Q_45" Value="0" MCT="24"/>
			<Cell CellID="Q_46" Value="0" MCT="25"/>
			<Cell CellID="Q_47" Value="0" MCT="26"/>
			<Cell CellID="Q_48" Value="0" MCT="27"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="H_56" Value=""/>
			<Cell CellID="R_56" Value=""/>
			<Cell CellID="H_58" Value=""/>
			<Cell CellID="R_58" Value=""/>
			<Cell CellID="C_61" Value=""/>
			<Cell CellID="F_61" Value=""/>
			<Cell CellID="I_61" Value=""/>
			<Cell CellID="L_61" Value=""/>
		</Cells>
	</Section>	
</Sections>

=== nvanhai/tct2013/Source/NTKCC3.1.7/TaxProjectServer/DataFiles/02_1_NTNN_002010.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_10" Value=""/>
			<Cell CellID="H_8" Value=""/>
			<Cell CellID="F_12" Value=""/>
			<Cell CellID="F_16" Value=""/>
			<Cell CellID="N_16" Value=""/>
			<Cell CellID="V_16" Value=""/>
			<Cell CellID="E_31" Value=""/>
			<Cell CellID="E_33" Value=""/>
			<Cell CellID="M_33" Value=""/>
			<Cell CellID="V_33" Value=""/>
			<Cell CellID="M_31" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="T_38" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_37" Value=""/>
			<Cell CellID="M_37" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_31" Value=""/>
			<Cell CellID="H_18" Value=""/>
			<Cell CellID="F_22" Value=""/>
			<Cell CellID="F_27" Value=""/>
			<Cell CellID="N_27" Value=""/>
			<Cell CellID="V_27" Value=""/>
			<Cell CellID="H_29" Value=""/>
			<Cell CellID="N_29" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="E_23" FirstCell="0" Value="dsfasdfasd" MCT=""/>
			<Cell CellID="J_23" Value="" MCT=""/>
			<Cell CellID="O_23" Value="" MCT=""/>
			<Cell CellID="W_23" Value="" MCT=""/>
			<Cell CellID="AE_23" Value="" MCT=""/>
			<Cell CellID="AJ_23" Value="" MCT=""/>
			<Cell CellID="AO_23" Value="" MCT=""/>
			<Cell CellID="AS_23" Value="" MCT=""/>
			<Cell CellID="AY_23" Value="" MCT=""/>
			<Cell CellID="BG_23" Value="43253245345" MCT=""/>
			<Cell CellID="BQ_23" Value="" MCT=""/>
			<Cell CellID="BY_23" Value="2345234534" MCT=""/>
			<Cell CellID="CJ_23" Value="4" MCT=""/>
		</Cells>
		<Cells>
			<Cell CellID="E_24" FirstCell="1" Value="fasdfasdfsad" MCT=""/>
			<Cell CellID="J_24" Value="" MCT=""/>
			<Cell CellID="O_24" Value="" MCT=""/>
			<Cell CellID="W_24" Value="" MCT=""/>
			<Cell CellID="AE_24" Value="" MCT=""/>
			<Cell CellID="AJ_24" Value="" MCT=""/>
			<Cell CellID="AO_24" Value="" MCT=""/>
			<Cell CellID="AS_24" Value="" MCT=""/>
			<Cell CellID="AY_24" Value="" MCT=""/>
			<Cell CellID="BG_24" Value="43523453" MCT=""/>
			<Cell CellID="BQ_24" Value="" MCT=""/>
			<Cell CellID="BY_24" Value="52345342" MCT=""/>
			<Cell CellID="CJ_24" Value="6" MCT=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="BG_26" Value="43296768798" MCT=""/>
			<Cell CellID="BY_26" Value="2397579876" MCT=""/>
			<Cell CellID="CJ_26" Value="10" MCT=""/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/iNTKC3.2.0/NTKC/DataFiles/09KK_TNCN_002009.xml
<!-- Edited by hlnam FIS_CMC-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_4" Value=""/>
			<Cell CellID="G_5" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="M_8" Value=""/>
			<Cell CellID="V_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="M_10" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_16" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_14" Value=""/>
			<Cell CellID="M_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_10" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_35" Value="07/2009"/>
			<Cell CellID="I_35" Value="12/2009"/>
			<Cell CellID="D_36" Value=""/>
			<Cell CellID="I_36" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="U_40" Value="400000000" MCT="1"/>
			<Cell CellID="U_41" Value="200000000" MCT="2"/>
			<Cell CellID="U_42" Value="200000000" MCT="3"/>
			<Cell CellID="U_43" Value="100000000" MCT="4"/>
			<Cell CellID="U_44" Value="0" MCT="5"/>
			<Cell CellID="U_45" Value="0" MCT="6"/>
			<Cell CellID="U_46" Value="0" MCT="7"/>
			<Cell CellID="U_47" Value="43200000" MCT="8"/>
			<Cell CellID="U_48" Value="24000000" MCT="9"/>
			<Cell CellID="U_49" Value="19200000" MCT="10"/>
			<Cell CellID="U_50" Value="0" MCT="11"/>
			<Cell CellID="U_51" Value="0" MCT="12"/>
			<Cell CellID="U_52" Value="356800000" MCT="13"/>
			<Cell CellID="U_53" Value="71940001" MCT="14"/>
			<Cell CellID="U_54" Value="36000000" MCT="15"/>
			<Cell CellID="U_55" Value="10000000" MCT="16"/>
			<Cell CellID="U_56" Value="26000000" MCT="17"/>
			<Cell CellID="U_57" Value="0" MCT="18"/>
			<Cell CellID="U_58" Value="0" MCT="19"/>
			<Cell CellID="U_59" Value="35940001" MCT="20"/>
			<Cell CellID="U_60" Value="0" MCT="21"/>
			<Cell CellID="U_61" Value="0" MCT="22"/>
			<Cell CellID="U_62" Value="0" MCT="23"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="R_64" Value="Nguyen Van An"/>
			<Cell CellID="R_66" Value="25/03/2010"/>
			<Cell CellID="C_67" Value="1"/>
			<Cell CellID="F_67" Value=""/>
			<Cell CellID="I_67" Value=""/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/DataFiles/01_TAIN11_072011.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="I_7" Value=""/>
			<Cell CellID="I_5" Value=""/>
			<Cell CellID="I_9" Value=""/>
			<Cell CellID="I_11" Value=""/>
			<Cell CellID="S_11" Value=""/>
			<Cell CellID="AG_11" Value=""/>
			<Cell CellID="F_23" Value=""/>
			<Cell CellID="F_25" Value=""/>
			<Cell CellID="S_25" Value=""/>
			<Cell CellID="AG_25" Value=""/>
			<Cell CellID="S_23" Value=""/>
			<Cell CellID="V_39" Value=""/>
			<Cell CellID="G_29" Value=""/>
			<Cell CellID="N_29" Value=""/>
			<Cell CellID="AG_23" Value=""/>
			<Cell CellID="I_13" Value=""/>
			<Cell CellID="I_17" Value=""/>
			<Cell CellID="I_19" Value=""/>
			<Cell CellID="S_19" Value="" MaxLen="60"/>
			<Cell CellID="AG_19" Value=""/>
			<Cell CellID="I_21" Value=""/>
			<Cell CellID="S_21" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="I_15" Value="6868686868"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_51" FirstCell="0" Value="010102" MCT="2"/>
			<Cell CellID="M_51" Value="Kg" MCT="3"/>
			<Cell CellID="P_51" Value="300.00" MCT="4"/>
			<Cell CellID="S_51" Value="200000.00" MCT="5"/>
			<Cell CellID="X_51" Value="10.000" MCT="6"/>
			<Cell CellID="AA_51" Value="0" MCT="7"/>
			<Cell CellID="AI_51" Value="0.00" MCT="8"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_55" FirstCell="0" Value="010103" MCT="11"/>
			<Cell CellID="M_55" Value="Kg" MCT="12"/>
			<Cell CellID="P_55" Value="50.00" MCT="13"/>
			<Cell CellID="S_55" Value="4000000.00" MCT="14"/>
			<Cell CellID="X_55" Value="11.000" MCT="15"/>
			<Cell CellID="AA_55" Value="0" MCT="16"/>
			<Cell CellID="AI_55" Value="0.00" MCT="17"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="T_59" Value="test"/>
			<Cell CellID="T_61" Value="asdasdad"/>
			<Cell CellID="AI_59" Value=""/>
			<Cell CellID="AI_61" Value="09/08/2011"/>
			<Cell CellID="D_33" Value="1"/>
			<Cell CellID="G_33" Value=""/>
			<Cell CellID="J_33" Value="0"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKCC3.1.7/TaxProjectServer/InterfaceTemplates/CatalogueQTTN_2008_01.xml
<!-- edited by Htphuong (CMCSoft - HN) -->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="C_4a" Value="2###0101a###Khoáng sản kim loại đen###Kg###2###0###1###1553"/>
			<Cell CellID="C_4b" Value="71###0101b###Khoáng sản kim loại đen###Kg###5###0###1###1553"/>
			<Cell CellID="C_5" Value="3###010101###Khoáng sản sắt, mangan, crôm, titan###Kg###5###0###1###1553"/>
			<Cell CellID="C_7" Value="5###010201###Vàng sa khoáng###Kg###6###0###1###1554"/>
			<Cell CellID="C_8" Value="6###010202###Vàng cốm###Kg###6###0###1###1554"/>
			<Cell CellID="C_9a" Value="7###010203a###Đất hiếm###Kg###4###0###1###1554"/>
			<Cell CellID="C_9b" Value="76###010203b###Đất hiếm###Kg###8###0###1###1554"/>
			<Cell CellID="C_10" Value="8###010204###Bạch kim, thiếc, Won fram, bạc, antimoan###Kg###5###0###1###1554"/>
			<Cell CellID="C_11a" Value="9###010205a###Chì,kẽm,nhôm,bô xít,đồng,niken, coban, Hg, Mg ...###Kg###3###0###1###1553"/>
			<Cell CellID="C_11b" Value="78###010205b###Chì,kẽm,nhôm,bô xít,đồng,niken, coban, Hg, Mg ...###Kg###5###0###1###1553"/>
			<Cell CellID="C_12a" Value="10###010206a###Các loại khoáng sản kim loại màu khác###Kg###2###0###1###1553"/>
			<Cell CellID="C_12b" Value="79###010206b###Các loại khoáng sản kim loại màu khác###Kg###5###0###1###1553"/>
			<Cell CellID="C_15" Value="13###020101###Đất khai thác, san lấp, xây đắp công trình###M3###1###0###1###1555"/>
			<Cell CellID="C_16a" Value="14###020102a###K.sản không k loại dùng làm VLXD khác (đá,cát,sỏi)###M3###2###0###1###1555"/>
			<Cell CellID="C_16b" Value="83###020102b###K.sản không k loại dùng làm VLXD khác (đá,cát,sỏi)###M3###4###0###1###1555"/>
			<Cell CellID="C_18a" Value="16###020201a###Granit, đô nô mit, sét chịu lửa ..###M3###3###0###1###1555"/>
			<Cell CellID="C_18b" Value="85###020201b###Granit, đô nô mit, sét chịu lửa ..###M3###5###0###1###1555"/>
			<Cell CellID="C_20" Value="18###020301###Apatít, Secpăngtin###M3###2###0###1###1555"/>
			<Cell CellID="C_21a" Value="67###020302a###Pirit,Phosphosit,cao lanh,mica,...###M3###4###0###1###1555"/>
			<Cell CellID="C_21b" Value="88###020302b###Pirit,Phosphosit,cao lanh,mica,...###M3###5###0###1###1555"/>
			<Cell CellID="C_22" Value="19###0206###Khoáng sản không kim loại khác###M3###2###0###1###1555"/>
			<Cell CellID="C_24a" Value="21###0301a###Than an tra xit hầm lò###Tấn###1###0###1###1555"/>
			<Cell CellID="C_24b" Value="91###0301b###Than an tra xit hầm lò###Tấn###2###0###1###1555"/>
			<Cell CellID="C_25a" Value="22###0302a###Than an tra xit lộ thiên###Tấn###2###0###1###1555"/>
			<Cell CellID="C_25b" Value="92###0302b###Than an tra xit lộ thiên###Tấn###3###0###1###1555"/>
			<Cell CellID="C_26" Value="23###0303###Than nâu, than mỡ###Tấn###3###0###1###1555"/>
			<Cell CellID="C_27" Value="24###0304###Than khác###Tấn###2###0###1###1555"/>
			<Cell CellID="C_29" Value="26###0401###Kim cương, rubi, saphia ...###M3###8###0###1###1554"/>
			<Cell CellID="C_30" Value="27###0402###Adrit, rô đô lit, py rốp, ...###M3###5###0###1###1554"/>
			<Cell CellID="C_31" Value="28###0403###Các loại đá quý khác###M3###3###0###1###1554"/>
			<Cell CellID="C_33" Value="30###0501###Dầu mỏ###Tấn###18###1###1###1551"/>
			<Cell CellID="C_35" Value="32###0601###Khí đốt###M3###8###1###1###1551"/>
			<Cell CellID="C_38" Value="35###070101###Gỗ nhóm 1###M3###40###0###1###1557"/>
			<Cell CellID="C_39" Value="36###070102###Gỗ nhóm 2###M3###35###0###1###1557"/>
			<Cell CellID="C_40" Value="37###070103###Gỗ nhóm 3 , 4###M3###25###0###1###1557"/>
			<Cell CellID="C_41" Value="38###070104###Gỗ nhóm 5,6,7,8###M3###15###0###1###1557"/>
			<Cell CellID="C_42" Value="39###0702###Gỗ Trụ mỏ###M3###15###0###1###1557"/>
			<Cell CellID="C_43" Value="40###0703###Gỗ làm nguyên liệu giấy###M3###20###0###1###1557"/>
			<Cell CellID="C_44" Value="41###0704###Gỗ cột buồm, cọc đáy###M3###20###0###1###1557"/>
			<Cell CellID="C_45a" Value="42###0705a###Gỗ tẩm, đước###M3###25###0###1###1557"/>
			<Cell CellID="C_45b" Value="112###0705b###Gỗ tẩm, đước###M3###15###0###1###1557"/>
			<Cell CellID="C_46" Value="43###0706###Gỗ cành, ngọn, củi###M3###5###0###1###1557"/>
			<Cell CellID="C_47" Value="44###0707###Tre, nứa..###M3###10###0###1###1557"/>
			<Cell CellID="C_49" Value="46###070801###Trầm hương, bakích, kỳ nam###Kg###25###0###1###1557"/>
			<Cell CellID="C_50" Value="47###070802###Hồi , quế, sa nhân, thảo quả###Kg###10###0###1###1557"/>
			<Cell CellID="C_51" Value="48###070803###Các loại dược liệu khác###Kg###5###0###1###1557"/>
			<Cell CellID="C_53" Value="50###070901###Chim thú rừng (loại được phép khai thác)###Kg###20###0###1###1557"/>
			<Cell CellID="C_54" Value="51###070902###Sản phẩm rừng tự nhiên khác###Kg###5###0###1###1557"/>
			<Cell CellID="C_56" Value="53###0801###Ngọc trai, bào ngư, hải sâm###Kg###10###0###1###1556"/>
			<Cell CellID="C_57" Value="54###0802###Tôm cá mực và các loại thuỷ sản khác###Kg###2###0###1###1556"/>
			<Cell CellID="C_59a" Value="56###0901a###Nước khoáng TN, nước TN tinh lọc đóng chai hộp###M3###4###0###1###1599"/>
			<Cell CellID="C_59b" Value="126###0901b###Nước khoáng TN, nước TN tinh lọc đóng chai hộp###M3###8###0###1###1599"/>
			<Cell CellID="C_60" Value="57###0902###Nước TN dùng sản xuất thuỷ điện###KW/h###2###0###1###1552"/>
			<Cell CellID="C_62" Value="59###090301###Nước TN sử dụng làm NL tạo thành yếu tố VC trong SXSF###M3###3###0###1###1599"/>
			<Cell CellID="C_63" Value="60###090302###Nước TN sử dụng chung phục vụ SX###M3###1###0###1###1599"/>
			<Cell CellID="C_64" Value="61###090303###Nước TN dùng SX nước sạch, phục vụ khác###M3###0###0###1###1599"/>
			<Cell CellID="C_65" Value="62###0904###Nước TN khai thác dùng vào các mục đích khác###M3###0###0###1###1599"/>
			<Cell CellID="C_67" Value="64###1001###Yến sào###Kg###20###0###1###1599"/>
			<Cell CellID="C_69" Value="66###1101###Tài nguyên khác###Kg###10###1###1###1599"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/DataFiles/01_NTNN_052012.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="H_7" Value=""/>
			<Cell CellID="H_5" Value=""/>
			<Cell CellID="H_9" Value=""/>
			<Cell CellID="H_11" Value=""/>
			<Cell CellID="R_11" Value=""/>
			<Cell CellID="AF_11" Value=""/>
			<Cell CellID="E_23" Value=""/>
			<Cell CellID="E_25" Value=""/>
			<Cell CellID="R_25" Value=""/>
			<Cell CellID="AF_25" Value=""/>
			<Cell CellID="R_23" Value=""/>
			<Cell CellID="V_39" Value=""/>
			<Cell CellID="F_27" Value=""/>
			<Cell CellID="E_29" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="AF_23" Value=""/>
			<Cell CellID="H_13" Value=""/>
			<Cell CellID="H_17" Value=""/>
			<Cell CellID="H_19" Value=""/>
			<Cell CellID="R_19" Value=""/>
			<Cell CellID="AF_19" Value=""/>
			<Cell CellID="H_21" Value=""/>
			<Cell CellID="R_21" Value=""/>
			<Cell CellID="AF_27" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="H_15" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_52" FirstCell="0" Value="1. PhÝ b#n quy•n th¸ng 5/2012 ()" MCT="1"/>
			<Cell CellID="H_52" Value="" MCT="2"/>
			<Cell CellID="L_52" Value="H ngµy 15/04/2007" MCT="3"/>
			<Cell CellID="Q_52" Value="241731965" MCT="4"/>
			<Cell CellID="V_52" Value="" MCT="5"/>
			<Cell CellID="Y_52" Value="265905162" MCT="6"/>
			<Cell CellID="AB_52" Value="0.0" MCT="7"/>
			<Cell CellID="AD_52" Value="0" MCT="8"/>
			<Cell CellID="AF_52" Value="0" MCT="9"/>
			<Cell CellID="AH_52" Value="241731965" MCT="10"/>
			<Cell CellID="AN_52" Value="10.0" MCT="11"/>
			<Cell CellID="AP_52" Value="0" MCT="12"/>
			<Cell CellID="AR_52" Value="24173197" MCT="13"/>
			<Cell CellID="AV_52" Value="24173197" MCT="14"/>
		</Cells>
		<Cells>
			<Cell CellID="C_53" FirstCell="1" Value="2. PhÝ b#n quy•n  ()" MCT="1"/>
			<Cell CellID="H_53" Value="" MCT="2"/>
			<Cell CellID="L_53" Value="H MK062" MCT="3"/>
			<Cell CellID="Q_53" Value="10500000" MCT="4"/>
			<Cell CellID="V_53" Value="" MCT="5"/>
			<Cell CellID="Y_53" Value="11550000" MCT="6"/>
			<Cell CellID="AB_53" Value="0.0" MCT="7"/>
			<Cell CellID="AD_53" Value="0" MCT="8"/>
			<Cell CellID="AF_53" Value="0" MCT="9"/>
			<Cell CellID="AH_53" Value="10500000" MCT="10"/>
			<Cell CellID="AN_53" Value="10.0" MCT="11"/>
			<Cell CellID="AP_53" Value="0" MCT="12"/>
			<Cell CellID="AR_53" Value="1050000" MCT="13"/>
			<Cell CellID="AV_53" Value="1050000" MCT="14"/>
		</Cells>
		<Cells>
			<Cell CellID="C_54" FirstCell="1" Value="3. PhÝ b#n quy¸n ()" MCT="1"/>
			<Cell CellID="H_54" Value="" MCT="2"/>
			<Cell CellID="L_54" Value="Statement Acc 30/4/2012" MCT="3"/>
			<Cell CellID="Q_54" Value="2694300" MCT="4"/>
			<Cell CellID="V_54" Value="" MCT="5"/>
			<Cell CellID="Y_54" Value="2963730" MCT="6"/>
			<Cell CellID="AB_54" Value="0.0" MCT="7"/>
			<Cell CellID="AD_54" Value="0" MCT="8"/>
			<Cell CellID="AF_54" Value="0" MCT="9"/>
			<Cell CellID="AH_54" Value="2694300" MCT="10"/>
			<Cell CellID="AN_54" Value="10.0" MCT="11"/>
			<Cell CellID="AP_54" Value="0" MCT="12"/>
			<Cell CellID="AR_54" Value="269430" MCT="13"/>
			<Cell CellID="AV_54" Value="269430" MCT="14"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="Y_56" Value="280418892" MCT="15"/>
			<Cell CellID="AF_56" Value="0" MCT="16"/>
			<Cell CellID="AH_56" Value="254926265" MCT="17"/>
			<Cell CellID="AP_56" Value="0" MCT="18"/>
			<Cell CellID="AR_56" Value="25492627" MCT="19"/>
			<Cell CellID="AV_56" Value="25492627" MCT="20"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="Z_3" Value="X"/>
			<Cell CellID="AD_3" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="E_41" Value=""/>
			<Cell CellID="E_42" Value=""/>
			<Cell CellID="J_41" Value="kydientu"/>
			<Cell CellID="J_42" Value="18/06/2012"/>
			<Cell CellID="C_40" Value="1"/>
			<Cell CellID="F_40" Value=""/>
			<Cell CellID="I_40" Value=""/>
			<Cell CellID="AG_42" Value="05/2012"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/iNTKC3.2.0/NTKC/DataFiles/01_TTDB11_042012.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="I_7" Value=""/>
			<Cell CellID="I_5" Value=""/>
			<Cell CellID="I_9" Value=""/>
			<Cell CellID="I_11" Value=""/>
			<Cell CellID="S_11" Value=""/>
			<Cell CellID="AG_11" Value=""/>
			<Cell CellID="F_23" Value=""/>
			<Cell CellID="F_25" Value=""/>
			<Cell CellID="S_25" Value=""/>
			<Cell CellID="AG_25" Value=""/>
			<Cell CellID="S_23" Value=""/>
			<Cell CellID="M_39" Value=""/>
			<Cell CellID="G_29" Value=""/>
			<Cell CellID="S_29" Value=""/>
			<Cell CellID="AG_23" Value=""/>
			<Cell CellID="I_13" Value=""/>
			<Cell CellID="I_17" Value=""/>
			<Cell CellID="I_19" Value=""/>
			<Cell CellID="S_19" Value="" MaxLen="60"/>
			<Cell CellID="AG_19" Value=""/>
			<Cell CellID="I_21" Value=""/>
			<Cell CellID="S_21" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="I_15" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="N_49" Value="" MCT="1"/>
			<Cell CellID="X_51" Value="9000000" MCT="2"/>
			<Cell CellID="AC_51" Value="6206897.00" MCT="3"/>
			<Cell CellID="AH_51" Value="900000" MCT="4"/>
			<Cell CellID="AK_51" Value="0"/>
			<Cell CellID="AO_51" Value="1893103" MCT="5"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_53" FirstCell="0" Value="10200" MCT="6"/>
			<Cell CellID="P_53" Value="LÝt" MCT="7"/>
			<Cell CellID="S_53" Value="100.00" MCT="8"/>
			<Cell CellID="X_53" Value="4000000" MCT="9"/>
			<Cell CellID="AC_53" Value="2758621.00" MCT="10"/>
			<Cell CellID="AE_53" Value="45.0" MCT="11"/>
			<Cell CellID="AH_53" Value="300000" MCT="12"/>
			<Cell CellID="AK_53" Value="0" MCT="13"/>
			<Cell CellID="AO_53" Value="941379" MCT="14"/>
		</Cells>
		<Cells>
			<Cell CellID="C_54" FirstCell="1" Value="10300" MCT="6"/>
			<Cell CellID="P_54" Value="LÝt" MCT="7"/>
			<Cell CellID="S_54" Value="200.00" MCT="8"/>
			<Cell CellID="X_54" Value="5000000" MCT="9"/>
			<Cell CellID="AC_54" Value="3448276.00" MCT="10"/>
			<Cell CellID="AE_54" Value="45.0" MCT="11"/>
			<Cell CellID="AH_54" Value="600000" MCT="12"/>
			<Cell CellID="AK_54" Value="0" MCT="13"/>
			<Cell CellID="AO_54" Value="951724" MCT="14"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="X_56" Value="10000000" MCT="15"/>
			<Cell CellID="AC_56" Value="7692308.00" MCT="16"/>
			<Cell CellID="AH_56" Value="600000" MCT="17"/>
			<Cell CellID="AK_56" Value="0"/>
			<Cell CellID="AO_56" Value="1707693" MCT="18"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_58" Value="20300" FirstCell="0" MCT="19"/>
			<Cell CellID="P_58" Value="" MCT="20"/>
			<Cell CellID="S_58" Value="300.00" MCT="21"/>
			<Cell CellID="X_58" Value="8000000" MCT="22"/>
			<Cell CellID="AC_58" Value="6153846.00" MCT="23"/>
			<Cell CellID="AE_58" Value="30.0" MCT="24"/>
			<Cell CellID="AH_58" Value="500000" MCT="25"/>
			<Cell CellID="AK_58" Value="0" MCT="26"/>
			<Cell CellID="AO_58" Value="1346154" MCT="27"/>
		</Cells>
		<Cells>
			<Cell CellID="C_59" Value="20102" FirstCell="1" MCT="19"/>
			<Cell CellID="P_59" Value="" MCT="20"/>
			<Cell CellID="S_59" Value="600.00" MCT="21"/>
			<Cell CellID="X_59" Value="2000000" MCT="22"/>
			<Cell CellID="AC_59" Value="1538462.00" MCT="23"/>
			<Cell CellID="AE_59" Value="30.0" MCT="24"/>
			<Cell CellID="AH_59" Value="100000" MCT="25"/>
			<Cell CellID="AK_59" Value="0" MCT="26"/>
			<Cell CellID="AO_59" Value="361539" MCT="27"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="X_61" Value="0" MCT="28"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_65" FirstCell="0" Value="" MCT="29"/>
			<Cell CellID="P_65" Value="" MCT="30"/>
			<Cell CellID="S_65" Value="0.00" MCT="31"/>
			<Cell CellID="X_65" Value="0" MCT="32"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_69" FirstCell="0" Value="" MCT="33"/>
			<Cell CellID="P_69" Value="" MCT="34"/>
			<Cell CellID="S_69" Value="0.00" MCT="35"/>
			<Cell CellID="X_69" Value="0" MCT="36"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_73" FirstCell="0" Value="" MCT="37"/>
			<Cell CellID="P_73" Value="" MCT="38"/>
			<Cell CellID="S_73" Value="0.00" MCT="39"/>
			<Cell CellID="X_73" Value="0" MCT="40"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="X_75" Value="19000000" MCT="41"/>
			<Cell CellID="AC_75" Value="13899205.00" MCT="42"/>
			<Cell CellID="AH_75" Value="1500000" MCT="43"/>
			<Cell CellID="AK_75" Value="0"/>
			<Cell CellID="AO_75" Value="3600796" MCT="44"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="AF_77" Value="rtgtggtfhgh"/>
			<Cell CellID="U_77" Value=""/>
			<Cell CellID="U_79" Value=""/>
			<Cell CellID="AF_79" Value="08/05/2012"/>
			<Cell CellID="D_33" Value="0"/>
			<Cell CellID="G_33" Value="1"/>
			<Cell CellID="J_33" Value="1"/>
			<Cell CellID="K_33" Value="3600796"/>
			<Cell CellID="L_33" Value=""/>
			<Cell CellID="M_33" Value="0"/>
		</Cells>
	</Section>
</Sections>
