=== nvanhai/tct2013/Source/HTKK3.1.7/InterfaceIni/Schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by tuyends (FSS-HCM) -->
<!ATTLIST Cell
	CellID ID #REQUIRED
	MaxLen CDATA #IMPLIED
	MinValue CDATA #IMPLIED
	MaxValue CDATA #IMPLIED
	HelpContextID CDATA #REQUIRED
>
<!ELEMENT Dynamic (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Cell (#PCDATA)>
<!ELEMENT Cells (Cell+)>
<!ATTLIST Sections
	Version CDATA #IMPLIED
>
<!ATTLIST Section
	Dynamic CDATA #REQUIRED
	MaxRows CDATA #REQUIRED
>
<!ELEMENT Section (Cells+)>
<!ELEMENT Sections (Section+)>

=== nvanhai/tct2013/Source/NTKCC3.1.7/TaxProjectServer/InterfaceTemplates/KHBS_01B_TNDN.xml
<!-- edited by Htphuong CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="A_5" Value=""/>
			<Cell CellID="B_6" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="F_8" Value=""/>
			<Cell CellID="G_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="G_12" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="BD_9" FirstCell="0" Value="" />
			<Cell CellID="BE_9" Value="" />
			<Cell CellID="BF_9" Value="0" />
			<Cell CellID="BG_9" Value="0" />
			<Cell CellID="BH_9" Value="0" />
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0" >
		<Cells>
			<Cell CellID="BD_13" FirstCell="0" Value="" />
			<Cell CellID="BE_13" Value="" />
			<Cell CellID="BF_13" Value="0" />
			<Cell CellID="BG_13" Value="0" />
			<Cell CellID="BH_13" Value="0" />
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>	
			<Cell CellID="BG_23" Value=""/>
			<Cell CellID="BE_17" Value="0"/>
			<Cell CellID="BE_18" Value="0"/>
			<Cell CellID="BD_20" Value=""/>
			<Cell CellID="BH_15" Value=""/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_BCTC/DataFiles/KHBS_01_NTNN_042012.xml
<!-- edited by nvanhai CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_8" Value=""/>
			<Cell CellID="G_7" Value=""/>
			<Cell CellID="G_9" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="E_22" Value=""/>
			<Cell CellID="E_24" Value=""/>
			<Cell CellID="M_24" Value=""/>
			<Cell CellID="V_24" Value=""/>
			<Cell CellID="M_22" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_29" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_28" Value=""/>
			<Cell CellID="M_28" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_22" Value=""/>
			<Cell CellID="K_14" Value=""/>
			<Cell CellID="G_16" Value=""/>
			<Cell CellID="E_18" Value=""/>
			<Cell CellID="M_18" Value=""/>
			<Cell CellID="V_18" Value=""/>
			<Cell CellID="I_19" Value=""/>
			<Cell CellID="S_19" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="BD_9" FirstCell="0" Value="" MCT="1"/>
			<Cell CellID="BE_9" Value="" MCT="2"/>
			<Cell CellID="BF_9" Value="0" MCT="3"/>
			<Cell CellID="BG_9" Value="0" MCT="4"/>
			<Cell CellID="BH_9" Value="0" MCT="5"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="BD_13" FirstCell="0" Value="" MCT="6"/>
			<Cell CellID="BE_13" Value="" MCT="7"/>
			<Cell CellID="BF_13" Value="0" MCT="8"/>
			<Cell CellID="BG_13" Value="0" MCT="9"/>
			<Cell CellID="BH_13" Value="0" MCT="10"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="B_24" Value="08/05/2012"/>
			<Cell CellID="BE_17" Value="92" MCT="12"/>
			<Cell CellID="BE_18" Value="0" MCT="13"/>
			<Cell CellID="BD_20" Value="" MCT="14"/>
			<Cell CellID="BH_15" Value="0" MCT="15"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/iNTKC3.2.0/NTKC/DataFiles/01_4A_GTGT11_072011.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="H_8" Value="Ngô Thanh Tuấn"/>
			<Cell CellID="F_10" Value=""/>
			<Cell CellID="F_12" Value=""/>
			<Cell CellID="F_16" Value=""/>
			<Cell CellID="N_16" Value=""/>
			<Cell CellID="V_16" Value=""/>
			<Cell CellID="E_30" Value=""/>
			<Cell CellID="E_32" Value=""/>
			<Cell CellID="M_32" Value=""/>
			<Cell CellID="V_32" Value=""/>
			<Cell CellID="M_30" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_39" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_36" Value=""/>
			<Cell CellID="M_36" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="D_4" Value="70697137" MCT="1"/>
			<Cell CellID="D_6" Value="0" MCT="2"/>
			<Cell CellID="D_8" Value="70697137" MCT="3"/>
			<Cell CellID="D_10" Value="0" MCT="4"/>
			<Cell CellID="D_15" Value="25682068673" MCT="5"/>
			<Cell CellID="D_16" Value="0" MCT="6"/>
			<Cell CellID="D_17" Value="0" MCT="7"/>
			<Cell CellID="D_18" Value="0" MCT="8"/>
			<Cell CellID="D_19" Value="0" MCT="9"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_BCTC/DataFiles/01B_TNDN11_012012.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_10" Value=""/>
			<Cell CellID="H_8" Value=""/>
			<Cell CellID="F_12" Value=""/>
			<Cell CellID="F_16" Value=""/>
			<Cell CellID="N_16" Value=""/>
			<Cell CellID="V_16" Value=""/>
			<Cell CellID="E_30" Value=""/>
			<Cell CellID="E_32" Value=""/>
			<Cell CellID="M_32" Value=""/>
			<Cell CellID="V_32" Value=""/>
			<Cell CellID="M_30" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_39" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_36" Value=""/>
			<Cell CellID="M_36" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_30" Value=""/>
			<Cell CellID="H_18" Value=""/>
			<Cell CellID="F_22" Value=""/>
			<Cell CellID="F_26" Value=""/>
			<Cell CellID="N_26" Value=""/>
			<Cell CellID="V_26" Value=""/>
			<Cell CellID="H_28" Value=""/>
			<Cell CellID="N_28" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_20" Value="0100100865"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="H_7" Value=""/>
			<Cell CellID="U_41" Value="3000000" MCT="21"/>
			<Cell CellID="U_42" Value="1000000" MCT="22"/>
			<Cell CellID="U_43" Value="2000000" MCT="23"/>
			<Cell CellID="U_44" Value="12.345" MCT="24"/>
			<Cell CellID="U_46" Value="12.456" MCT="25"/>
			<Cell CellID="K_47" Value=""/>
			<Cell CellID="U_47" Value="15.789" MCT="26"/>
			<Cell CellID="U_48" Value="54360" MCT="27"/>
			<Cell CellID="U_49" Value="15377" MCT="28"/>
			<Cell CellID="U_50" Value="38983" MCT="29"/>
			<Cell CellID="U_52" Value="0" MCT="30"/>
			<Cell CellID="U_53" Value="54360" MCT="31"/>
			<Cell CellID="E_38" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="T_57" Value=""/>
			<Cell CellID="T_59" Value="03/05/2012"/>
			<Cell CellID="H_57" Value="25465"/>
			<Cell CellID="H_59" Value="5456"/>
			<Cell CellID="C_62" Value="1"/>
			<Cell CellID="I_62" Value=""/>
			<Cell CellID="L_62" Value="1052"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/DataFiles/03A_TNCN11_072011.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_8" Value=""/>
			<Cell CellID="G_7" Value=""/>
			<Cell CellID="G_9" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="E_22" Value=""/>
			<Cell CellID="E_24" Value=""/>
			<Cell CellID="M_24" Value=""/>
			<Cell CellID="V_24" Value=""/>
			<Cell CellID="M_22" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_29" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_28" Value=""/>
			<Cell CellID="M_28" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_22" Value=""/>
			<Cell CellID="K_14" Value=""/>
			<Cell CellID="G_16" Value=""/>
			<Cell CellID="E_18" Value=""/>
			<Cell CellID="M_18" Value=""/>
			<Cell CellID="V_18" Value=""/>
			<Cell CellID="I_19" Value=""/>
			<Cell CellID="S_19" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_15" Value="6868686868"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="S_42" Value="10000000" MCT="2"/>
			<Cell CellID="S_43" Value="500000" MCT="3"/>
			<Cell CellID="S_45" Value="2000000" MCT="5"/>
			<Cell CellID="S_46" Value="2000" MCT="6"/>
			<Cell CellID="S_48" Value="1000000" MCT="8"/>
			<Cell CellID="S_49" Value="50000" MCT="9"/>
			<Cell CellID="S_52" Value="100000" MCT="11"/>
			<Cell CellID="S_53" Value="10000" MCT="12"/>
			<Cell CellID="S_55" Value="10000000" MCT="14"/>
			<Cell CellID="S_56" Value="10000" MCT="15"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="R_58" Value=""/>
			<Cell CellID="R_60" Value="08/08/2011"/>
			<Cell CellID="G_58" Value="test"/>
			<Cell CellID="G_60" Value="asdasdad"/>
			<Cell CellID="C_61" Value="1"/>
			<Cell CellID="F_61" Value=""/>
			<Cell CellID="I_61" Value=""/>
			<Cell CellID="B_41" Value="I" MCT="I" Receive="0"/>
			<Cell CellID="B_44" Value="II" MCT="II" Receive="0"/>
			<Cell CellID="B_47" Value="III" MCT="III" Receive="0"/>
			<Cell CellID="B_50" Value="IV" MCT="IV" Receive="0"/>
			<Cell CellID="B_54" Value="V" MCT="V" Receive="0"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/iNTKC3.2.0/NTKC/DataFiles/03_TNDN_002009.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_4" Value=""/>
			<Cell CellID="G_5" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="M_8" Value=""/>
			<Cell CellID="V_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="M_10" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_16" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_14" Value=""/>
			<Cell CellID="M_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_10" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="W_18" Value="0" MCT="A1"/>
			<Cell CellID="W_20" Value="0" MCT="B1"/>
			<Cell CellID="W_21" Value="0" MCT="B2"/>
			<Cell CellID="W_22" Value="0" MCT="B3"/>
			<Cell CellID="W_23" Value="0" MCT="B4"/>
			<Cell CellID="W_24" Value="0" MCT="B5"/>
			<Cell CellID="W_25" Value="0" MCT="B6"/>
			<Cell CellID="W_26" Value="0" MCT="B7"/>
			<Cell CellID="W_27" Value="0" MCT="B8"/>
			<Cell CellID="W_28" Value="0" MCT="B9"/>
			<Cell CellID="W_29" Value="0" MCT="B10"/>
			<Cell CellID="W_30" Value="0" MCT="B11"/>
			<Cell CellID="W_31" Value="0" MCT="B12"/>
			<Cell CellID="W_32" Value="0" MCT="B13"/>
			<Cell CellID="W_33" Value="0" MCT="B14"/>
			<Cell CellID="W_34" Value="0" MCT="B15"/>
			<Cell CellID="W_35" Value="0" MCT="B16"/>
			<Cell CellID="W_36" Value="0" MCT="B17"/>
			<Cell CellID="W_37" Value="0" MCT="B18"/>
			<Cell CellID="W_38" Value="0" MCT="B19"/>
			<Cell CellID="W_39" Value="0" MCT="B20"/>
			<Cell CellID="W_40" Value="0" MCT="B21"/>
			<Cell CellID="W_41" Value="0" MCT="B22"/>
			<Cell CellID="W_42" Value="0" MCT="B23"/>
			<Cell CellID="W_43" Value="0" MCT="B24"/>
			<Cell CellID="W_44" Value="0" MCT="B25"/>
			<Cell CellID="W_45" Value="0" MCT="B26"/>
			<Cell CellID="W_46" Value="0" MCT="B27"/>
			<Cell CellID="W_47" Value="0" MCT="B28"/>
			<Cell CellID="W_48" Value="0" MCT="B29"/>
			<Cell CellID="W_49" Value="0" MCT="B30"/>
			<Cell CellID="W_50" Value="0" MCT="B31"/>
			<Cell CellID="W_52" Value="0" MCT="C1"/>
			<Cell CellID="W_53" Value="0" MCT="C2"/>
			<Cell CellID="W_54" Value="0" MCT="C3"/>
			<Cell CellID="W_55" Value="0" MCT="C4"/>
			<Cell CellID="W_56" Value="0" MCT="C5"/>
			<Cell CellID="W_57" Value="0" MCT="C6"/>
			<Cell CellID="W_58" Value="0" MCT="C7"/>
			<Cell CellID="W_59" Value="0" MCT="C8"/>
			<Cell CellID="W_60" Value="0" MCT="C9"/>
			<Cell CellID="W_61" Value="0" MCT="C10"/>
			<Cell CellID="C_63" Value="" MCT="D1"/>
			<Cell CellID="C_64" Value="" MCT="D2"/>
			<Cell CellID="C_65" Value="" MCT="D3"/>
			<Cell CellID="C_66" Value="" MCT="D4"/>
			<Cell CellID="C_67" Value="" MCT="D5"/>
			<Cell CellID="C_68" Value="" MCT="D6"/>
			<Cell CellID="E_15" Value=""/>
			<Cell CellID="V_70" Value=""/>
			<Cell CellID="V_72" Value="09/04/2010"/>
			<Cell CellID="W_17" Value="0" MCT="A"/>
			<Cell CellID="W_19" Value="0" MCT="B"/>
			<Cell CellID="W_51" Value="0" MCT="C"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/DataFiles/06_TNCN11_002011.xml
<!-- Edited by hlnam FIS_CMC-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_10" Value=""/>
			<Cell CellID="H_8" Value=""/>
			<Cell CellID="F_12" Value=""/>
			<Cell CellID="F_16" Value=""/>
			<Cell CellID="N_16" Value=""/>
			<Cell CellID="V_16" Value=""/>
			<Cell CellID="E_30" Value=""/>
			<Cell CellID="E_32" Value=""/>
			<Cell CellID="M_32" Value=""/>
			<Cell CellID="V_32" Value=""/>
			<Cell CellID="M_30" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_39" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_36" Value=""/>
			<Cell CellID="M_36" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_30" Value=""/>
			<Cell CellID="H_18" Value=""/>
			<Cell CellID="F_22" Value=""/>
			<Cell CellID="F_26" Value=""/>
			<Cell CellID="N_26" Value=""/>
			<Cell CellID="V_26" Value=""/>
			<Cell CellID="H_28" Value=""/>
			<Cell CellID="N_28" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_20" Value="2222222222"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="U_43" Value="1000000000" MCT="21"/>
			<Cell CellID="U_44" Value="50000000" MCT="22"/>
			<Cell CellID="U_46" Value="100000000" MCT="23"/>
			<Cell CellID="U_47" Value="0" MCT="24"/>
			<Cell CellID="U_49" Value="0" MCT="25"/>
			<Cell CellID="U_50" Value="0" MCT="26"/>
			<Cell CellID="U_52" Value="53453534" MCT="27"/>
			<Cell CellID="U_53" Value="345353" MCT="28"/>
			<Cell CellID="U_55" Value="34534534535" MCT="29"/>
			<Cell CellID="U_56" Value="345345" MCT="30"/>
			<Cell CellID="U_57" Value="345345345" MCT="31"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="T_61" Value="iiiii"/>
			<Cell CellID="T_63" Value="10/01/2012"/>
			<Cell CellID="G_61" Value="Â¸df"/>
			<Cell CellID="G_63" Value="sdfsdf"/>
			<Cell CellID="C_64" Value="1"/>
			<Cell CellID="I_64" Value=""/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/DataFiles/48_02_SXKD_002009.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_4" Value=""/>
			<Cell CellID="G_5" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="M_8" Value=""/>
			<Cell CellID="V_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="M_10" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_16" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_14" Value=""/>
			<Cell CellID="M_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_10" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="P_39" Value="IV.08" MCT="46" RowID="1"/>
			<Cell CellID="R_39" Value="11000000" MCT="47" RowID="1"/>
			<Cell CellID="W_39" Value="1000000" MCT="48" RowID="1"/>
			<Cell CellID="P_40" Value="" MCT="1" RowID="2"/>
			<Cell CellID="R_40" Value="10000000" MCT="2" RowID="2"/>
			<Cell CellID="W_40" Value="0" MCT="3" RowID="2"/>
			<Cell CellID="P_41" Value="" MCT="4" RowID="3"/>
			<Cell CellID="R_41" Value="1000000" MCT="5" RowID="3"/>
			<Cell CellID="W_41" Value="1000000" MCT="6" RowID="3"/>
			<Cell CellID="P_42" Value="" MCT="7" RowID="4"/>
			<Cell CellID="R_42" Value="0" MCT="8" RowID="4"/>
			<Cell CellID="W_42" Value="0" MCT="9" RowID="4"/>
			<Cell CellID="P_43" Value="" MCT="10" RowID="5"/>
			<Cell CellID="R_43" Value="1000000" MCT="11" RowID="5"/>
			<Cell CellID="W_43" Value="1000000" MCT="12" RowID="5"/>
			<Cell CellID="P_44" Value="" MCT="13" RowID="6"/>
			<Cell CellID="R_44" Value="0" MCT="14" RowID="6"/>
			<Cell CellID="W_44" Value="0" MCT="15" RowID="6"/>
			<Cell CellID="P_45" Value="" MCT="16" RowID="7"/>
			<Cell CellID="R_45" Value="0" MCT="17" RowID="7"/>
			<Cell CellID="W_45" Value="10000000" MCT="18" RowID="7"/>
			<Cell CellID="P_46" Value="" MCT="19" RowID="8"/>
			<Cell CellID="R_46" Value="0" MCT="20" RowID="8"/>
			<Cell CellID="W_46" Value="0" MCT="21" RowID="8"/>
			<Cell CellID="P_47" Value="" MCT="22" RowID="9"/>
			<Cell CellID="R_47" Value="0" MCT="23" RowID="9"/>
			<Cell CellID="W_47" Value="0" MCT="24" RowID="9"/>
			<Cell CellID="P_48" Value="" MCT="25" RowID="10"/>
			<Cell CellID="R_48" Value="1000000" MCT="26" RowID="10"/>
			<Cell CellID="W_48" Value="-9000000" MCT="27" RowID="10"/>
			<Cell CellID="P_49" Value="" MCT="28" RowID="11"/>
			<Cell CellID="R_49" Value="0" MCT="29" RowID="11"/>
			<Cell CellID="W_49" Value="0" MCT="30" RowID="11"/>
			<Cell CellID="P_50" Value="" MCT="31" RowID="12"/>
			<Cell CellID="R_50" Value="0" MCT="32" RowID="12"/>
			<Cell CellID="W_50" Value="0" MCT="33" RowID="12"/>
			<Cell CellID="P_51" Value="" MCT="34" RowID="13"/>
			<Cell CellID="R_51" Value="0" MCT="35" RowID="13"/>
			<Cell CellID="W_51" Value="0" MCT="36" RowID="13"/>
			<Cell CellID="P_52" Value="IV.09" MCT="37" RowID="14"/>
			<Cell CellID="R_52" Value="1000000" MCT="38" RowID="14"/>
			<Cell CellID="W_52" Value="-9000000" MCT="39" RowID="14"/>
			<Cell CellID="P_53" Value="" MCT="40" RowID="15"/>
			<Cell CellID="R_53" Value="0" MCT="41" RowID="15"/>
			<Cell CellID="W_53" Value="0" MCT="42" RowID="15"/>
			<Cell CellID="P_54" Value="" MCT="43" RowID="16"/>
			<Cell CellID="R_54" Value="1000000" MCT="44" RowID="16"/>
			<Cell CellID="W_54" Value="-9000000" MCT="45" RowID="16"/>
			<Cell CellID="R_56" Value="toan"/>
			<Cell CellID="R_58" Value="14/06/2010"/>
		</Cells>
	</Section>
</Sections>
