=== nvanhai/tct2013/Source/HTKK3.1.7/InterfaceIni/Schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by tuyends (FSS-HCM) -->
<!ATTLIST Cell
	CellID ID #REQUIRED
	MaxLen CDATA #IMPLIED
	MinValue CDATA #IMPLIED
	MaxValue CDATA #IMPLIED
	HelpContextID CDATA #REQUIRED
>
<!ELEMENT Dynamic (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Cell (#PCDATA)>
<!ELEMENT Cells (Cell+)>
<!ATTLIST Sections
	Version CDATA #IMPLIED
>
<!ATTLIST Section
	Dynamic CDATA #REQUIRED
	MaxRows CDATA #REQUIRED
>
<!ELEMENT Section (Cells+)>
<!ELEMENT Sections (Section+)>

=== nvanhai/tct2013/Source/iNTKC3.1.7/NTKC/DataFiles/01_02_TTDB_052010.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_4" Value=""/>
			<Cell CellID="G_5" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="M_8" Value=""/>
			<Cell CellID="V_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="M_10" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_16" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_14" Value=""/>
			<Cell CellID="M_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_10" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_24" FirstCell="0" Value="a1" MCT="2"/>
			<Cell CellID="D_24" Value="12312" MCT="3"/>
			<Cell CellID="E_24" Value="01/01/2010" MCT="4"/>
			<Cell CellID="F_24" Value="test" MCT="5"/>
			<Cell CellID="G_24" Value="10000.00" MCT="6"/>
			<Cell CellID="H_24" Value="100000" MCT="7"/>
			<Cell CellID="J_24" Value="0" MCT="9"/>
			<Cell CellID="K_24" Value="100000" MCT="10"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_34" FirstCell="0" Value="test1" MCT="15"/>
			<Cell CellID="E_34" Value="200.00" MCT="16"/>
			<Cell CellID="F_34" Value="as" MCT="17"/>
			<Cell CellID="H_34" Value="20.00" MCT="18"/>
			<Cell CellID="J_34" Value="150.00" MCT="19"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC_TMS/InterfaceTemplates/xml/02_TNCN_BH11.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_10" Value=""/>
			<Cell CellID="H_8" Value=""/>
			<Cell CellID="F_12" Value=""/>
			<Cell CellID="F_16" Value=""/>
			<Cell CellID="N_16" Value=""/>
			<Cell CellID="V_16" Value=""/>
			<Cell CellID="E_30" Value=""/>
			<Cell CellID="E_32" Value=""/>
			<Cell CellID="M_32" Value=""/>
			<Cell CellID="V_32" Value=""/>
			<Cell CellID="M_30" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_39" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_36" Value=""/>
			<Cell CellID="M_36" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_30" Value=""/>

			<Cell CellID="H_18" Value=""/>
			<Cell CellID="F_22" Value=""/>
			<Cell CellID="F_26" Value=""/>
			<Cell CellID="N_26" Value=""/>
			<Cell CellID="V_26" Value=""/>
			<Cell CellID="H_28" Value=""/>
			<Cell CellID="N_28" Value=""/>			
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_20" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="S_42" Value="" MCT="21" />
			<Cell CellID="S_43" Value="" MCT="22" />
			<Cell CellID="S_44" Value="" MCT="23" />
			<Cell CellID="S_45" Value="" MCT="24" />
			<Cell CellID="S_46" Value="" MCT="25" />
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="T_58" Value=""/>
			<Cell CellID="T_60" Value=""/>
			<Cell CellID="H_58" Value=""/>
			<Cell CellID="H_60" Value=""/>
			<Cell CellID="C_62" Value=""/>
			<Cell CellID="I_62" Value=""/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/HTKK3.3/InterfaceIni/04_NTNN.xml
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections >
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="N_21" MaxLen="300" MinValue="" MaxValue="" HelpContextID="80121"/>		
			<Cell CellID="AH_21" MaxLen="10" MinValue="" MaxValue="" HelpContextID="80121"/>
			
			<Cell CellID="T_30" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82122"/>		
			<Cell CellID="T_31" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82126"/>
			<Cell CellID="T_32" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82130"/>			
			<Cell CellID="T_33" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82134"/>
			<Cell CellID="T_34" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82138"/>
			<Cell CellID="T_35" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82142"/>
			<Cell CellID="T_36" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82146"/>
			
			<Cell CellID="AB_30" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82123"/>		
			<Cell CellID="AB_31" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82127"/>
			<Cell CellID="AB_32" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82131"/>			
			<Cell CellID="AB_33" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82135"/>
			<Cell CellID="AB_34" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82139"/>
			<Cell CellID="AB_35" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82143"/>
			<Cell CellID="AB_36" MaxLen="" MinValue="0" MaxValue="999999999999999" HelpContextID="82147"/>
			
			<Cell CellID="AJ_30" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82124"/>		
			<Cell CellID="AJ_31" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82128"/>
			<Cell CellID="AJ_32" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82132"/>			
			<Cell CellID="AJ_33" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82136"/>
			<Cell CellID="AJ_34" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82140"/>
			<Cell CellID="AJ_35" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82144"/>
			<Cell CellID="AJ_36" MaxLen="" MinValue="-999999999999999" MaxValue="999999999999999" HelpContextID="82148"/>
			
			
			<Cell CellID="AT_30" MaxLen="300" MinValue="" MaxValue="" HelpContextID="82125"/>		
			<Cell CellID="AT_31" MaxLen="300" MinValue="" MaxValue="" HelpContextID="82129"/>
			<Cell CellID="AT_32" MaxLen="300" MinValue="" MaxValue="" HelpContextID="82133"/>			
			<Cell CellID="AT_33" MaxLen="300" MinValue="" MaxValue="" HelpContextID="82137"/>
			<Cell CellID="AT_34" MaxLen="300" MinValue="" MaxValue="" HelpContextID="82141"/>
			<Cell CellID="AT_35" MaxLen="300" MinValue="" MaxValue="" HelpContextID="82145"/>
			<Cell CellID="AT_36" MaxLen="300" MinValue="" MaxValue="" HelpContextID="82149"/>
		</Cells>
	</Section>
		<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="M_44" MaxLen="50" MinValue="" MaxValue="" HelpContextID="82100"/>
			<Cell CellID="M_46" MaxLen="50" MinValue="" MaxValue="" HelpContextID="82100"/>
			<Cell CellID="AL_44" MaxLen="50" MinValue="" MaxValue="" HelpContextID="82100"/>
			<Cell CellID="AL_46" MaxLen="10" MinValue="" MaxValue="" HelpContextID="82100"/>			
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/HTKK3.2/InterfaceIni/Catalogue_011900_01.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSOFT -->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections Version="120">
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="B_2" HelpContextID="0"/>
			<Cell CellID="B_4" HelpContextID="0"/>
			<Cell CellID="B_5" HelpContextID="0"/>
			<Cell CellID="B_7" HelpContextID="0"/>
			<Cell CellID="B_8" HelpContextID="0"/>
			<Cell CellID="B_9" HelpContextID="0"/>
			<Cell CellID="B_10" HelpContextID="0"/>
			<Cell CellID="B_11" HelpContextID="0"/>
			<Cell CellID="B_12" HelpContextID="0"/>
			<Cell CellID="B_15" HelpContextID="0"/>
			<Cell CellID="B_16" HelpContextID="0"/>
			<Cell CellID="B_18" HelpContextID="0"/>
			<Cell CellID="B_20" HelpContextID="0"/>
			<Cell CellID="B_21" HelpContextID="0"/>
			<Cell CellID="B_22" HelpContextID="0"/>
			<Cell CellID="B_24" HelpContextID="0"/>
			<Cell CellID="B_25" HelpContextID="0"/>
			<Cell CellID="B_26" HelpContextID="0"/>
			<Cell CellID="B_27" HelpContextID="0"/>
			<Cell CellID="B_29" HelpContextID="0"/>
			<Cell CellID="B_30" HelpContextID="0"/>
			<Cell CellID="B_31" HelpContextID="0"/>
			<Cell CellID="B_33" HelpContextID="0"/>
			<Cell CellID="B_35" HelpContextID="0"/>
			<Cell CellID="B_38" HelpContextID="0"/>
			<Cell CellID="B_39" HelpContextID="0"/>
			<Cell CellID="B_40" HelpContextID="0"/>
			<Cell CellID="B_41" HelpContextID="0"/>
			<Cell CellID="B_42" HelpContextID="0"/>
			<Cell CellID="B_43" HelpContextID="0"/>
			<Cell CellID="B_44" HelpContextID="0"/>
			<Cell CellID="B_45" HelpContextID="0"/>
			<Cell CellID="B_46" HelpContextID="0"/>
			<Cell CellID="B_47" HelpContextID="0"/>
			<Cell CellID="B_49" HelpContextID="0"/>
			<Cell CellID="B_50" HelpContextID="0"/>
			<Cell CellID="B_51" HelpContextID="0"/>
			<Cell CellID="B_53" HelpContextID="0"/>
			<Cell CellID="B_54" HelpContextID="0"/>
			<Cell CellID="B_56" HelpContextID="0"/>
			<Cell CellID="B_57" HelpContextID="0"/>
			<Cell CellID="B_59" HelpContextID="0"/>
			<Cell CellID="B_60" HelpContextID="0"/>
			<Cell CellID="B_62" HelpContextID="0"/>
			<Cell CellID="B_63" HelpContextID="0"/>
			<Cell CellID="B_64" HelpContextID="0"/>
			<Cell CellID="B_65" HelpContextID="0"/>
			<Cell CellID="B_67" HelpContextID="0"/>
			<Cell CellID="B_69" HelpContextID="0"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/InterfaceTemplates/xml/02_TNDN14.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_10" Value=""/>
			<Cell CellID="H_8" Value=""/>
			<Cell CellID="F_12" Value=""/>
			<Cell CellID="F_16" Value=""/>
			<Cell CellID="N_16" Value=""/>
			<Cell CellID="V_16" Value=""/>
			<Cell CellID="E_42" Value=""/>
			<Cell CellID="E_44" Value=""/>
			<Cell CellID="M_44" Value=""/>
			<Cell CellID="V_44" Value=""/>
			<Cell CellID="M_42" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_49" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_48" Value=""/>
			<Cell CellID="M_48" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_42" Value=""/>
			<Cell CellID="H_30" Value=""/>
			<Cell CellID="F_34" Value=""/>
			<Cell CellID="F_38" Value=""/>
			<Cell CellID="N_38" Value=""/>
			<Cell CellID="V_38" Value=""/>
			<Cell CellID="H_40" Value=""/>
			<Cell CellID="N_40" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_32" Value=""/>
		</Cells>
	</Section>	
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="V_55"   Value=""  MCT="25"/>
  	       <Cell CellID="V_56"   Value=""  MCT="26"/>
  	       <Cell CellID="V_57"   Value=""  MCT="27"/>
  	       <Cell CellID="V_58"   Value=""  MCT="28"/>
  	       <Cell CellID="V_59"   Value=""  MCT="29"/>
  	       <Cell CellID="V_60"   Value=""  MCT="30"/>
  	       <Cell CellID="V_61"   Value=""  MCT="31"/>
  	       <Cell CellID="V_62"   Value=""  MCT="32"/>
  	       <Cell CellID="V_63"   Value=""  MCT="33"/>
  	       <Cell CellID="V_66"   Value=""  MCT="34"/>
  	       <Cell CellID="V_67"   Value=""  MCT="35"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>			
			<Cell CellID="P_49"   Value=""/>
			<Cell CellID="Q_49"   Value=""/>
		   <Cell CellID="K_20"   Value=""  MCT="46"/>
  	       <Cell CellID="R_22"   Value=""  MCT="47"/>
		   <Cell CellID="E_24"   Value=""  MCT="48"/>
  	       <Cell CellID="K_26"   Value=""  MCT="49"/>
  	       <Cell CellID="N_26"   Value=""  MCT="50"/>
  	       <Cell CellID="Q_28"   Value=""  MCT="51"/>
		</Cells>
	</Section>	
	<Section Dynamic="0" MaxRows="0">
		<Cells>
		   	<Cell CellID="G_78"   Value=""/>
			<Cell CellID="G_80"   Value=""/>
  	       <Cell CellID="T_78"   Value=""/>  	       
  	       <Cell CellID="T_80"   Value=""/>
		   <Cell CellID="M_49"   Value=""/>
  	       <Cell CellID="O_49"   Value=""/>
  	       <Cell CellID="M_50"   Value=""/>
			<Cell CellID="E_47"   Value=""/>
		   <Cell CellID="H_7"   Value=""/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_BCTC/DataFiles/BC26_AC_012012.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="E_4" Value=""/>
			<Cell CellID="E_5" Value=""/>
			<Cell CellID="E_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="K_8" Value=""/>
			<Cell CellID="Q_8" Value=""/>
			<Cell CellID="E_18" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="K_12" Value=""/>
			<Cell CellID="Q_12" Value=""/>
			<Cell CellID="K_10" Value=""/>
			<Cell CellID="K_18" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="E_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="Q_10" Value=""/>
			<Cell CellID="Q_14" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="E_16" Value="" MCT=""/>
			<Cell CellID="K_16" Value="" MCT=""/>
			<Cell CellID="E_23" Value="01/01/2012" MCT=""/>
			<Cell CellID="F_23" Value="31/03/2012" MCT=""/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="D_32" FirstCell="0" Value="Hãa ®¬n gi¸ trÞ gia t¨ng" MCT="1"/>
			<Cell CellID="J_32" Value="01GTKT3/001" MCT="2"/>
			<Cell CellID="K_32" Value="AA/01T" MCT="3"/>
			<Cell CellID="L_32" Value="100" MCT="4"/>
			<Cell CellID="M_32" Value="" MCT="5"/>
			<Cell CellID="N_32" Value="" MCT="6"/>
			<Cell CellID="O_32" Value="0000001" MCT="7"/>
			<Cell CellID="P_32" Value="0000100" MCT="8"/>
			<Cell CellID="Q_32" Value="" MCT="9"/>
			<Cell CellID="R_32" Value="" MCT="10"/>
			<Cell CellID="S_32" Value="0" MCT="11"/>
			<Cell CellID="U_32" Value="0" MCT="12"/>
			<Cell CellID="V_32" Value="0" MCT="13"/>
			<Cell CellID="W_32" Value="" MCT="14"/>
			<Cell CellID="X_32" Value="0" MCT="15"/>
			<Cell CellID="Y_32" Value="" MCT="16"/>
			<Cell CellID="Z_32" Value="0" MCT="17"/>
			<Cell CellID="AA_32" Value="" MCT="18"/>
			<Cell CellID="AC_32" Value="0000001" MCT="19"/>
			<Cell CellID="AD_32" Value="0000100" MCT="20"/>
			<Cell CellID="AE_32" Value="100" MCT="21"/>
			<Cell CellID="AF_32" Value="0" MCT="22"/>
		</Cells>
		<Cells>
			<Cell CellID="D_33" FirstCell="1" Value="Hãa ®¬n gi¸ trÞ gia t¨ng" MCT="1"/>
			<Cell CellID="J_33" Value="01GTKT3/001" MCT="2"/>
			<Cell CellID="K_33" Value="AB/01T" MCT="3"/>
			<Cell CellID="L_33" Value="100" MCT="4"/>
			<Cell CellID="M_33" Value="" MCT="5"/>
			<Cell CellID="N_33" Value="" MCT="6"/>
			<Cell CellID="O_33" Value="0000001" MCT="7"/>
			<Cell CellID="P_33" Value="0000100" MCT="8"/>
			<Cell CellID="Q_33" Value="" MCT="9"/>
			<Cell CellID="R_33" Value="" MCT="10"/>
			<Cell CellID="S_33" Value="0" MCT="11"/>
			<Cell CellID="U_33" Value="0" MCT="12"/>
			<Cell CellID="V_33" Value="0" MCT="13"/>
			<Cell CellID="W_33" Value="" MCT="14"/>
			<Cell CellID="X_33" Value="0" MCT="15"/>
			<Cell CellID="Y_33" Value="" MCT="16"/>
			<Cell CellID="Z_33" Value="0" MCT="17"/>
			<Cell CellID="AA_33" Value="" MCT="18"/>
			<Cell CellID="AC_33" Value="0000001" MCT="19"/>
			<Cell CellID="AD_33" Value="0000100" MCT="20"/>
			<Cell CellID="AE_33" Value="100" MCT="21"/>
			<Cell CellID="AF_33" Value="0" MCT="22"/>
		</Cells>
		<Cells>
			<Cell CellID="D_34" FirstCell="1" Value="Hãa ®¬n gi¸ trÞ gia t¨ng" MCT="1"/>
			<Cell CellID="J_34" Value="01GTKT3/001" MCT="2"/>
			<Cell CellID="K_34" Value="AC/01T" MCT="3"/>
			<Cell CellID="L_34" Value="100" MCT="4"/>
			<Cell CellID="M_34" Value="" MCT="5"/>
			<Cell CellID="N_34" Value="" MCT="6"/>
			<Cell CellID="O_34" Value="0000001" MCT="7"/>
			<Cell CellID="P_34" Value="0000100" MCT="8"/>
			<Cell CellID="Q_34" Value="" MCT="9"/>
			<Cell CellID="R_34" Value="" MCT="10"/>
			<Cell CellID="S_34" Value="0" MCT="11"/>
			<Cell CellID="U_34" Value="0" MCT="12"/>
			<Cell CellID="V_34" Value="0" MCT="13"/>
			<Cell CellID="W_34" Value="" MCT="14"/>
			<Cell CellID="X_34" Value="0" MCT="15"/>
			<Cell CellID="Y_34" Value="" MCT="16"/>
			<Cell CellID="Z_34" Value="0" MCT="17"/>
			<Cell CellID="AA_34" Value="" MCT="18"/>
			<Cell CellID="AC_34" Value="0000001" MCT="19"/>
			<Cell CellID="AD_34" Value="0000100" MCT="20"/>
			<Cell CellID="AE_34" Value="100" MCT="21"/>
			<Cell CellID="AF_34" Value="0" MCT="22"/>
		</Cells>
		<Cells>
			<Cell CellID="D_35" FirstCell="1" Value="Hãa ®¬n gi¸ trÞ gia t¨ng" MCT="1"/>
			<Cell CellID="J_35" Value="01GTKT3/001" MCT="2"/>
			<Cell CellID="K_35" Value="BB/01T" MCT="3"/>
			<Cell CellID="L_35" Value="100" MCT="4"/>
			<Cell CellID="M_35" Value="" MCT="5"/>
			<Cell CellID="N_35" Value="" MCT="6"/>
			<Cell CellID="O_35" Value="0000001" MCT="7"/>
			<Cell CellID="P_35" Value="0000100" MCT="8"/>
			<Cell CellID="Q_35" Value="" MCT="9"/>
			<Cell CellID="R_35" Value="" MCT="10"/>
			<Cell CellID="S_35" Value="0" MCT="11"/>
			<Cell CellID="U_35" Value="0" MCT="12"/>
			<Cell CellID="V_35" Value="0" MCT="13"/>
			<Cell CellID="W_35" Value="" MCT="14"/>
			<Cell CellID="X_35" Value="0" MCT="15"/>
			<Cell CellID="Y_35" Value="" MCT="16"/>
			<Cell CellID="Z_35" Value="0" MCT="17"/>
			<Cell CellID="AA_35" Value="" MCT="18"/>
			<Cell CellID="AC_35" Value="0000001" MCT="19"/>
			<Cell CellID="AD_35" Value="0000100" MCT="20"/>
			<Cell CellID="AE_35" Value="100" MCT="21"/>
			<Cell CellID="AF_35" Value="0" MCT="22"/>
		</Cells>
		<Cells>
			<Cell CellID="D_36" FirstCell="1" Value="Hãa ®¬n gi¸ trÞ gia t¨ng" MCT="1"/>
			<Cell CellID="J_36" Value="01GTKT3/001" MCT="2"/>
			<Cell CellID="K_36" Value="BC/01T" MCT="3"/>
			<Cell CellID="L_36" Value="100" MCT="4"/>
			<Cell CellID="M_36" Value="" MCT="5"/>
			<Cell CellID="N_36" Value="" MCT="6"/>
			<Cell CellID="O_36" Value="0000001" MCT="7"/>
			<Cell CellID="P_36" Value="0000100" MCT="8"/>
			<Cell CellID="Q_36" Value="" MCT="9"/>
			<Cell CellID="R_36" Value="" MCT="10"/>
			<Cell CellID="S_36" Value="0" MCT="11"/>
			<Cell CellID="U_36" Value="0" MCT="12"/>
			<Cell CellID="V_36" Value="0" MCT="13"/>
			<Cell CellID="W_36" Value="" MCT="14"/>
			<Cell CellID="X_36" Value="0" MCT="15"/>
			<Cell CellID="Y_36" Value="" MCT="16"/>
			<Cell CellID="Z_36" Value="0" MCT="17"/>
			<Cell CellID="AA_36" Value="" MCT="18"/>
			<Cell CellID="AC_36" Value="0000001" MCT="19"/>
			<Cell CellID="AD_36" Value="0000100" MCT="20"/>
			<Cell CellID="AE_36" Value="100" MCT="21"/>
			<Cell CellID="AF_36" Value="0" MCT="22"/>
		</Cells>
		<Cells>
			<Cell CellID="D_37" FirstCell="1" Value="Hãa ®¬n gi¸ trÞ gia t¨ng" MCT="1"/>
			<Cell CellID="J_37" Value="01GTKT3/001" MCT="2"/>
			<Cell CellID="K_37" Value="XK/02T" MCT="3"/>
			<Cell CellID="L_37" Value="100" MCT="4"/>
			<Cell CellID="M_37" Value="" MCT="5"/>
			<Cell CellID="N_37" Value="" MCT="6"/>
			<Cell CellID="O_37" Value="0000001" MCT="7"/>
			<Cell CellID="P_37" Value="0000100" MCT="8"/>
			<Cell CellID="Q_37" Value="" MCT="9"/>
			<Cell CellID="R_37" Value="" MCT="10"/>
			<Cell CellID="S_37" Value="0" MCT="11"/>
			<Cell CellID="U_37" Value="0" MCT="12"/>
			<Cell CellID="V_37" Value="0" MCT="13"/>
			<Cell CellID="W_37" Value="" MCT="14"/>
			<Cell CellID="X_37" Value="0" MCT="15"/>
			<Cell CellID="Y_37" Value="" MCT="16"/>
			<Cell CellID="Z_37" Value="0" MCT="17"/>
			<Cell CellID="AA_37" Value="" MCT="18"/>
			<Cell CellID="AC_37" Value="0000001" MCT="19"/>
			<Cell CellID="AD_37" Value="0000100" MCT="20"/>
			<Cell CellID="AE_37" Value="100" MCT="21"/>
			<Cell CellID="AF_37" Value="0" MCT="22"/>
		</Cells>
		<Cells>
			<Cell CellID="D_38" FirstCell="1" Value="Hãa ®¬n b¸n hµng" MCT="1"/>
			<Cell CellID="J_38" Value="02GTTT3/001" MCT="2"/>
			<Cell CellID="K_38" Value="BA/01T" MCT="3"/>
			<Cell CellID="L_38" Value="100" MCT="4"/>
			<Cell CellID="M_38" Value="" MCT="5"/>
			<Cell CellID="N_38" Value="" MCT="6"/>
			<Cell CellID="O_38" Value="0000001" MCT="7"/>
			<Cell CellID="P_38" Value="0000100" MCT="8"/>
			<Cell CellID="Q_38" Value="" MCT="9"/>
			<Cell CellID="R_38" Value="" MCT="10"/>
			<Cell CellID="S_38" Value="0" MCT="11"/>
			<Cell CellID="U_38" Value="0" MCT="12"/>
			<Cell CellID="V_38" Value="0" MCT="13"/>
			<Cell CellID="W_38" Value="" MCT="14"/>
			<Cell CellID="X_38" Value="0" MCT="15"/>
			<Cell CellID="Y_38" Value="" MCT="16"/>
			<Cell CellID="Z_38" Value="0" MCT="17"/>
			<Cell CellID="AA_38" Value="" MCT="18"/>
			<Cell CellID="AC_38" Value="0000001" MCT="19"/>
			<Cell CellID="AD_38" Value="0000100" MCT="20"/>
			<Cell CellID="AE_38" Value="100" MCT="21"/>
			<Cell CellID="AF_38" Value="0" MCT="22"/>
		</Cells>
		<Cells>
			<Cell CellID="D_39" FirstCell="1" Value="Hãa ®¬n xuÊt khÈu" MCT="1"/>
			<Cell CellID="J_39" Value="06HDXK2/001" MCT="2"/>
			<Cell CellID="K_39" Value="XK/01T" MCT="3"/>
			<Cell CellID="L_39" Value="100" MCT="4"/>
			<Cell CellID="M_39" Value="" MCT="5"/>
			<Cell CellID="N_39" Value="" MCT="6"/>
			<Cell CellID="O_39" Value="0000001" MCT="7"/>
			<Cell CellID="P_39" Value="0000100" MCT="8"/>
			<Cell CellID="Q_39" Value="" MCT="9"/>
			<Cell CellID="R_39" Value="" MCT="10"/>
			<Cell CellID="S_39" Value="0" MCT="11"/>
			<Cell CellID="U_39" Value="0" MCT="12"/>
			<Cell CellID="V_39" Value="0" MCT="13"/>
			<Cell CellID="W_39" Value="" MCT="14"/>
			<Cell CellID="X_39" Value="0" MCT="15"/>
			<Cell CellID="Y_39" Value="" MCT="16"/>
			<Cell CellID="Z_39" Value="0" MCT="17"/>
			<Cell CellID="AA_39" Value="" MCT="18"/>
			<Cell CellID="AC_39" Value="0000001" MCT="19"/>
			<Cell CellID="AD_39" Value="0000100" MCT="20"/>
			<Cell CellID="AE_39" Value="100" MCT="21"/>
			<Cell CellID="AF_39" Value="0" MCT="22"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="E_47" Value=""/>
			<Cell CellID="S_47" Value=""/>
			<Cell CellID="S_49" Value="18/07/2012"/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/DataFiles/03_NTNN11_042012.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_10" Value=""/>
			<Cell CellID="H_8" Value=""/>
			<Cell CellID="F_12" Value=""/>
			<Cell CellID="F_16" Value=""/>
			<Cell CellID="N_16" Value=""/>
			<Cell CellID="V_16" Value=""/>
			<Cell CellID="E_30" Value=""/>
			<Cell CellID="E_32" Value=""/>
			<Cell CellID="M_32" Value=""/>
			<Cell CellID="V_32" Value=""/>
			<Cell CellID="M_30" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_39" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_36" Value=""/>
			<Cell CellID="M_36" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_30" Value=""/>
			<Cell CellID="H_18" Value=""/>
			<Cell CellID="F_22" Value=""/>
			<Cell CellID="F_26" Value=""/>
			<Cell CellID="N_26" Value=""/>
			<Cell CellID="V_26" Value=""/>
			<Cell CellID="H_28" Value=""/>
			<Cell CellID="N_28" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="F_20" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="AV_44" FirstCell="0" Value="01" MCT="1"/>
			<Cell CellID="N_44" Value="" MCT="2"/>
			<Cell CellID="S_44" Value="" MCT="3"/>
			<Cell CellID="X_44" Value="0" MCT="4"/>
			<Cell CellID="AC_44" Value="" MCT="5"/>
			<Cell CellID="AF_44" Value="2000000000" MCT="6"/>
			<Cell CellID="AK_44" Value="1" MCT="7"/>
			<Cell CellID="AL_44" Value="0" MCT="8"/>
			<Cell CellID="AQ_44" Value="20000000" MCT="9"/>
		</Cells>
		<Cells>
			<Cell CellID="AV_45" FirstCell="1" Value="04" MCT="1"/>
			<Cell CellID="N_45" Value="" MCT="2"/>
			<Cell CellID="S_45" Value="" MCT="3"/>
			<Cell CellID="X_45" Value="0" MCT="4"/>
			<Cell CellID="AC_45" Value="" MCT="5"/>
			<Cell CellID="AF_45" Value="400000000" MCT="6"/>
			<Cell CellID="AK_45" Value="2" MCT="7"/>
			<Cell CellID="AL_45" Value="0" MCT="8"/>
			<Cell CellID="AQ_45" Value="8000000" MCT="9"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="X_47" Value="0" MCT="10"/>
			<Cell CellID="AF_47" Value="2400000000" MCT="11"/>
			<Cell CellID="AL_47" Value="0" MCT="12"/>
			<Cell CellID="AQ_47" Value="28000000" MCT="13"/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="P_37" Value="1"/>
			<Cell CellID="Q_37" Value=""/>
		</Cells>
	</Section>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="J_54" Value=""/>
			<Cell CellID="AH_54" Value="NguyÔn §×nh Phóc"/>
			<Cell CellID="J_56" Value=""/>
			<Cell CellID="AH_56" Value="08/05/2012"/>
			<Cell CellID="M_37" Value=""/>
			<Cell CellID="N_37" Value="1"/>
			<Cell CellID="O_37" Value="1"/>
			<Cell CellID="S_37" Value=""/>
		</Cells>
	</Section>
</Sections>

=== nvanhai/tct2013/Source/NTKC3.2_PIT/DataFiles/01_01_TTDB_052010.xml
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by CMCSoft-->
<!DOCTYPE Sections SYSTEM "Schema.dtd">
<Sections>
	<Section Dynamic="0" MaxRows="0">
		<Cells>
			<Cell CellID="G_4" Value=""/>
			<Cell CellID="G_5" Value=""/>
			<Cell CellID="G_6" Value=""/>
			<Cell CellID="E_8" Value=""/>
			<Cell CellID="M_8" Value=""/>
			<Cell CellID="V_8" Value=""/>
			<Cell CellID="E_10" Value=""/>
			<Cell CellID="E_12" Value=""/>
			<Cell CellID="M_12" Value=""/>
			<Cell CellID="V_12" Value=""/>
			<Cell CellID="M_10" Value="" MaxLen="20" HelpContexID="01_01_M_10"/>
			<Cell CellID="V_16" Value="" MinValue="0" MaxValue="9999999999" HelpContexID="01_01_V_10"/>
			<Cell CellID="E_14" Value=""/>
			<Cell CellID="M_14" Value="" MaxLen="100" HelpContexID="01_01_M_14"/>
			<Cell CellID="V_10" Value="" MaxLen="60"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="C_25" FirstCell="0" Value="DX/2010B" MCT="1"/>
			<Cell CellID="D_25" Value="0021535" MCT="2"/>
			<Cell CellID="E_25" Value="31/05/2010" MCT="3"/>
			<Cell CellID="F_25" Value="C+ng ty TNHH SXTMamp;DV S)m Ho5ng Nh)n" MCT="4"/>
			<Cell CellID="I_25" Value="10203" MCT="6"/>
			<Cell CellID="J_25" Value="R-nu s)m 1.2l/1cq" MCT="5"/>
			<Cell CellID="N_25" Value="6.48" MCT="7"/>
			<Cell CellID="O_25" Value="37090.82" MCT="8"/>
			<Cell CellID="P_25" Value="240349" MCT="9"/>
		</Cells>
		<Cells>
			<Cell CellID="C_26" FirstCell="1" Value="DX/2010B" MCT="1"/>
			<Cell CellID="D_26" Value="0021535" MCT="2"/>
			<Cell CellID="E_26" Value="31/05/2010" MCT="3"/>
			<Cell CellID="F_26" Value="C+ng ty TNHH SXTMamp;DV S)m Ho5ng Nh)n" MCT="4"/>
			<Cell CellID="I_26" Value="10203" MCT="6"/>
			<Cell CellID="J_26" Value="R-nu s)m 700ml/1cq" MCT="5"/>
			<Cell CellID="N_26" Value="2.52" MCT="7"/>
			<Cell CellID="O_26" Value="57974.00" MCT="8"/>
			<Cell CellID="P_26" Value="146094" MCT="9"/>
		</Cells>
	</Section>
	<Section Dynamic="1" MaxRows="0">
		<Cells>
			<Cell CellID="J_30" FirstCell="0" Value="R-nu d-mi 20 .i, r-nu hoa qu6, r-nu thuhc"/>
			<Cell CellID="N_30" Value="9.00"/>
			<Cell CellID="P_30" Value="386443"/>
		</Cells>
	</Section>
</Sections>
